# flake8: noqa: E501
"""
Django settings for simple project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from django.conf.locale.en import formats as en_formats

from simple.settings.logging import *
from simple.settings.spectacular import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(rc@3z2yacv8e5p(i4n5cn!3szxdnsl5&nm$_erhmoo9!z=*=*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["simple.dev.intra", "localhost", "0.0.0.0", "127.0.0.1"]

# OpenWeatherMap API settings
OPENWEATHER_API_KEY = os.environ.get('OPENWEATHER_API_KEY', 'your_api_key_here')

REST_FRAMEWORK = {
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S.%fZ",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "1000/minute", "user": "1000/minute"},
}

SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,
    "VALIDATOR_URL": None,
}


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "djmoney",
    "phonenumber_field",
    "rangefilter",
    "rest_framework",
    "import_export",
    "admin_numeric_filter",
    "django_admin_listfilter_dropdown",
    "django_filters",
    "admin_auto_filters",
    "django_extensions",
    "drf_yasg",
    "drf_spectacular",
    "django_apscheduler",
    "adminsortable2",
    "django_json_widget",
    "log_viewer",
    "django_dramatiq",
    "simple",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "simple.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],  # Добавлена директория для глобальных шаблонов
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "simple.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "simple"),
        "USER": os.environ.get("POSTGRES_USER", "simple"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "simple"),
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        # 'HOST': os.environ.get('POSTGRES_HOST', 'simple-db'),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "../volumes/db/db.sqlite3",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

DATETIME_FORMAT = "d.m.Y H:i:s"

# Admin Panel
en_formats.DATETIME_FORMAT = "d.m.Y H:i:s"
en_formats.DATE_FORMAT = "d.m.Y"
en_formats.TIME_FORMAT = "H:i:s"

DATE_FORMAT = "d.m.Y"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files configuration
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(PROJECT_ROOT, "../static")
STATICFILES_DIRS = []


# Media files configuration
MEDIA_URL = "/media/"
MEDIA_ROOT = "/app/media/"

# Security settings
ALLOWED_HOSTS = [
    "simple.dev.intra",
    "localhost",
    "10.0.0.1",
    "10.0.1.18",
    "172.18.0.2",
]
CSRF_TRUSTED_ORIGINS = ["https://simple.dev.intra"]

# Proxy settings
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Dramatiq settings
DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.rabbitmq.RabbitmqBroker",
    "OPTIONS": {
        "url": os.environ.get(
            "RABBITMQ_URL", "amqp://simple:simple@simple-rabbitmq:5672"
        ),
    },
    "MIDDLEWARE": [
        "dramatiq.middleware.Prometheus",
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Retries",
        "django_dramatiq.middleware.DbConnectionsMiddleware",
        "django_dramatiq.middleware.AdminMiddleware",
    ],
}

DRAMATIQ_RESULT_BACKEND = {
    "BACKEND": "dramatiq.results.backends.StubBackend",
    "BACKEND_OPTIONS": {},
}


DRAMATIQ_TASKS_DATABASE = "default"
OPENWEATHER_API_KEY = '8bf505cfa313a10d62328abdb5235e6d'
