# Generated by Django 5.1.5 on 2025-10-28 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Author's first name",
                        max_length=100,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Author's last name",
                        max_length=100,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True,
                        help_text="Author's biography",
                        verbose_name="Biography",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        help_text="Author's date of birth",
                        null=True,
                        verbose_name="Birth Date",
                    ),
                ),
                (
                    "death_date",
                    models.DateField(
                        blank=True,
                        help_text="Author's date of death",
                        null=True,
                        verbose_name="Death Date",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        help_text="Author's nationality",
                        max_length=100,
                        verbose_name="Nationality",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this author is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["last_name"], name="simple_auth_last_na_72310a_idx"),
                    models.Index(fields=["first_name"], name="simple_auth_first_n_0dff11_idx"),
                    models.Index(fields=["is_active"], name="simple_auth_is_acti_1b40e0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MovieCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g. Action, Drama, Comedy)",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is active and should be displayed",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Movie Category",
                "verbose_name_plural": "Movie Categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="simple_movi_name_9ac2a6_idx"),
                    models.Index(fields=["slug"], name="simple_movi_slug_7b2ea2_idx"),
                    models.Index(fields=["is_active"], name="simple_movi_is_acti_622679_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        help_text="Name of the city for weather data",
                        max_length=100,
                        verbose_name="City Name",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO country code (e.g., RU, US, GB)",
                        max_length=10,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Geographical longitude coordinate",
                        validators=[
                            django.core.validators.MinValueValidator(
                                -180.0, "Longitude too low"
                            ),
                            django.core.validators.MaxValueValidator(
                                180.0, "Longitude too high"
                            ),
                        ],
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Geographical latitude coordinate",
                        validators=[
                            django.core.validators.MinValueValidator(-90.0, "Latitude too low"),
                            django.core.validators.MaxValueValidator(90.0, "Latitude too high"),
                        ],
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "weather_id",
                    models.IntegerField(
                        help_text="OpenWeatherMap weather condition ID",
                        verbose_name="Weather ID",
                    ),
                ),
                (
                    "weather_main",
                    models.CharField(
                        help_text="Weather parameters group",
                        max_length=50,
                        verbose_name="Weather Main",
                    ),
                ),
                (
                    "weather_description",
                    models.CharField(
                        help_text="Weather condition within the group",
                        max_length=100,
                        verbose_name="Weather Description",
                    ),
                ),
                (
                    "weather_icon",
                    models.CharField(
                        help_text="Weather icon code",
                        max_length=10,
                        verbose_name="Weather Icon",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        help_text="Temperature value in Kelvin",
                        verbose_name="Temperature",
                    ),
                ),
                (
                    "feels_like",
                    models.FloatField(
                        help_text="Human perception of temperature",
                        verbose_name="Feels Like",
                    ),
                ),
                (
                    "temp_min",
                    models.FloatField(
                        help_text="Minimum temperature", verbose_name="Min Temperature"
                    ),
                ),
                (
                    "temp_max",
                    models.FloatField(
                        help_text="Maximum temperature", verbose_name="Max Temperature"
                    ),
                ),
                (
                    "pressure",
                    models.IntegerField(
                        help_text="Atmospheric pressure in hPa",
                        validators=[
                            django.core.validators.MinValueValidator(800, "Pressure too low"),
                            django.core.validators.MaxValueValidator(1100, "Pressure too high"),
                        ],
                        verbose_name="Pressure (hPa)",
                    ),
                ),
                (
                    "humidity",
                    models.IntegerField(
                        help_text="Humidity percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0, "Humidity too low"),
                            django.core.validators.MaxValueValidator(100, "Humidity too high"),
                        ],
                        verbose_name="Humidity (%)",
                    ),
                ),
                (
                    "visibility",
                    models.IntegerField(
                        blank=True,
                        help_text="Visibility in meters",
                        null=True,
                        verbose_name="Visibility (m)",
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        help_text="Wind speed in meters per second",
                        validators=[
                            django.core.validators.MinValueValidator(0.0, "Wind speed negative")
                        ],
                        verbose_name="Wind Speed (m/s)",
                    ),
                ),
                (
                    "wind_degree",
                    models.IntegerField(
                        help_text="Wind direction in degrees",
                        validators=[
                            django.core.validators.MinValueValidator(0, "Wind degree too low"),
                            django.core.validators.MaxValueValidator(
                                360, "Wind degree too high"
                            ),
                        ],
                        verbose_name="Wind Degree",
                    ),
                ),
                (
                    "clouds",
                    models.IntegerField(
                        help_text="Cloudiness percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0, "Cloudiness too low"),
                            django.core.validators.MaxValueValidator(
                                100, "Cloudiness too high"
                            ),
                        ],
                        verbose_name="Cloudiness (%)",
                    ),
                ),
                (
                    "sunrise",
                    models.DateTimeField(help_text="Sunrise time", verbose_name="Sunrise"),
                ),
                (
                    "sunset",
                    models.DateTimeField(help_text="Sunset time", verbose_name="Sunset"),
                ),
                (
                    "api_timestamp",
                    models.DateTimeField(
                        help_text="Time when data was received from API",
                        verbose_name="API Timestamp",
                    ),
                ),
                (
                    "timezone_offset",
                    models.IntegerField(
                        help_text="Shift in seconds from UTC",
                        verbose_name="Timezone Offset",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether weather record is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when record was updated",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["city_name"], name="simple_weat_city_na_a963df_idx"),
                    models.Index(
                        fields=["country_code"], name="simple_weat_country_968527_idx"
                    ),
                    models.Index(fields=["created_at"], name="simple_weat_created_f3d371_idx"),
                    models.Index(fields=["is_active"], name="simple_weat_is_acti_d8df4f_idx"),
                    models.Index(
                        fields=["weather_main"], name="simple_weat_weather_ea3631_idx"
                    ),
                    models.Index(fields=["temperature"], name="simple_weat_tempera_33d454_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Book title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "original_title",
                    models.CharField(
                        blank=True,
                        help_text="Original title if different",
                        max_length=255,
                        verbose_name="Original Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly title",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Book summary", verbose_name="Description"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        help_text="Book publication date",
                        null=True,
                        verbose_name="Publication Date",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="International Standard Book Number",
                        max_length=20,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of pages in the book",
                        null=True,
                        verbose_name="Page Count",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this book is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Book author",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="simple.author",
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["-publication_date", "title"],
                "indexes": [
                    models.Index(fields=["title"], name="simple_book_title_453799_idx"),
                    models.Index(fields=["slug"], name="simple_book_slug_8ea1bf_idx"),
                    models.Index(fields=["is_active"], name="simple_book_is_acti_8903d8_idx"),
                    models.Index(
                        fields=["publication_date"],
                        name="simple_book_publica_57f986_idx",
                    ),
                    models.Index(fields=["author"], name="simple_book_author__90a23c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Movie title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "original_title",
                    models.CharField(
                        blank=True,
                        help_text="Original title if different from main title",
                        max_length=255,
                        verbose_name="Original Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly title",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Movie plot summary",
                        verbose_name="Description",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Movie release date",
                        null=True,
                        verbose_name="Release Date",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Movie duration in minutes",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Duration must be at least 1 minute"
                            ),
                            django.core.validators.MaxValueValidator(
                                600, "Duration cannot exceed 600 minutes"
                            ),
                        ],
                        verbose_name="Duration (minutes)",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Movie rating (0-10)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "Rating cannot be less than 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                10.0, "Rating cannot exceed 10"
                            ),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True,
                        help_text="Movie director",
                        max_length=255,
                        verbose_name="Director",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this movie is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Movie category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movies",
                        to="simple.moviecategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "ordering": ["-release_date", "title"],
                "indexes": [
                    models.Index(fields=["title"], name="simple_movi_title_a7585e_idx"),
                    models.Index(fields=["slug"], name="simple_movi_slug_9a6cfb_idx"),
                    models.Index(fields=["is_active"], name="simple_movi_is_acti_de08f0_idx"),
                    models.Index(
                        fields=["release_date"], name="simple_movi_release_7bb684_idx"
                    ),
                    models.Index(fields=["rating"], name="simple_movi_rating_6ec672_idx"),
                    models.Index(fields=["category"], name="simple_movi_categor_abae47_idx"),
                ],
            },
        ),
    ]
