# Generated by Django 5.1.5 on 2025-04-21 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g. Action, Drama, Comedy)",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is active and should be displayed",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Movie Category",
                "verbose_name_plural": "Movie Categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="simple_movi_name_9ac2a6_idx"),
                    models.Index(fields=["slug"], name="simple_movi_slug_7b2ea2_idx"),
                    models.Index(
                        fields=["is_active"], name="simple_movi_is_acti_622679_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Movie title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "original_title",
                    models.CharField(
                        blank=True,
                        help_text="Original title if different from main title",
                        max_length=255,
                        verbose_name="Original Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly title",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Movie plot summary",
                        verbose_name="Description",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Movie release date",
                        null=True,
                        verbose_name="Release Date",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Movie duration in minutes",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Duration must be at least 1 minute"
                            ),
                            django.core.validators.MaxValueValidator(
                                600, "Duration cannot exceed 600 minutes"
                            ),
                        ],
                        verbose_name="Duration (minutes)",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Movie rating (0-10)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "Rating cannot be less than 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                10.0, "Rating cannot exceed 10"
                            ),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True,
                        help_text="Movie director",
                        max_length=255,
                        verbose_name="Director",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this movie is active and should be displayed",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Movie category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movies",
                        to="simple.moviecategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "ordering": ["-release_date", "title"],
                "indexes": [
                    models.Index(fields=["title"], name="simple_movi_title_a7585e_idx"),
                    models.Index(fields=["slug"], name="simple_movi_slug_9a6cfb_idx"),
                    models.Index(
                        fields=["is_active"], name="simple_movi_is_acti_de08f0_idx"
                    ),
                    models.Index(
                        fields=["release_date"], name="simple_movi_release_7bb684_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="simple_movi_rating_6ec672_idx"
                    ),
                    models.Index(
                        fields=["category"], name="simple_movi_categor_abae47_idx"
                    ),
                ],
            },
        ),
    ]
