# Generated by Django 5.1.5 on 2025-05-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this movie is active', verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Author's first name", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Author's last name", max_length=100, verbose_name='Last Name')),
                ('biography', models.TextField(blank=True, help_text="Author's biography", verbose_name='Biography')),
                ('birth_date', models.DateField(blank=True, help_text="Author's date of birth", null=True, verbose_name='Birth Date')),
                ('death_date', models.DateField(blank=True, help_text="Author's date of death", null=True, verbose_name='Death Date')),
                ('nationality', models.CharField(blank=True, help_text="Author's nationality", max_length=100, verbose_name='Nationality')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this author is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name'], name='simple_auth_last_na_72310a_idx'), models.Index(fields=['first_name'], name='simple_auth_first_n_0dff11_idx'), models.Index(fields=['is_active'], name='simple_auth_is_acti_1b40e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=255, verbose_name='Title')),
                ('original_title', models.CharField(blank=True, help_text='Original title if different', max_length=255, verbose_name='Original Title')),
                ('slug', models.SlugField(help_text='URL-friendly title', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Book summary', verbose_name='Description')),
                ('publication_date', models.DateField(blank=True, help_text='Book publication date', null=True, verbose_name='Publication Date')),
                ('isbn', models.CharField(blank=True, help_text='International Standard Book Number', max_length=20, verbose_name='ISBN')),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Number of pages in the book', null=True, verbose_name='Page Count')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this book is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('author', models.ForeignKey(help_text='Book author', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='simple.author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-publication_date', 'title'],
                'indexes': [models.Index(fields=['title'], name='simple_book_title_453799_idx'), models.Index(fields=['slug'], name='simple_book_slug_8ea1bf_idx'), models.Index(fields=['is_active'], name='simple_book_is_acti_8903d8_idx'), models.Index(fields=['publication_date'], name='simple_book_publica_57f986_idx'), models.Index(fields=['author'], name='simple_book_author__90a23c_idx')],
            },
        ),
    ]
