# Generated by Django 5.1.5 on 2025-05-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_alter_movie_is_active_alter_moviecategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category is active and should be displayed', verbose_name='Active'),
        ),
    ]
