# Generated by Django 5.1.5 on 2025-10-10 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_alter_author_biography_alter_author_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, help_text="Author's biography", verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Author's date of birth", null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, help_text="Author's date of death", null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text="Author's first name", max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this author is active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text="Author's last name", max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, help_text="Author's nationality", max_length=100, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Book author', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='simple.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Book summary', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this book is active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='International Standard Book Number', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, help_text='Original title if different', max_length=255, verbose_name='Original Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pages in the book', null=True, verbose_name='Page Count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Book publication date', null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(help_text='URL-friendly title', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Book title', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(help_text='Movie category', on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='simple.moviecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, help_text='Movie plot summary', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, help_text='Movie director', max_length=255, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Movie duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(1, 'Duration must be at least 1 minute'), django.core.validators.MaxValueValidator(600, 'Duration cannot exceed 600 minutes')], verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this movie is active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, help_text='Original title if different from main title', max_length=255, verbose_name='Original Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Movie rating (0-10)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Rating cannot be less than 0'), django.core.validators.MaxValueValidator(10.0, 'Rating cannot exceed 10')], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, help_text='Movie release date', null=True, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(help_text='URL-friendly title', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Movie title', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this category', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category is active and should be displayed', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='name',
            field=models.CharField(help_text='Category name (e.g. Action, Drama, Comedy)', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='slug',
            field=models.SlugField(help_text='URL-friendly name', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='api_timestamp',
            field=models.DateTimeField(help_text='Time when data was received from the API', verbose_name='API Timestamp'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city_name',
            field=models.CharField(help_text='Name of the city for which weather data was collected', max_length=100, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='clouds',
            field=models.IntegerField(help_text='Cloudiness percentage', validators=[django.core.validators.MinValueValidator(0, 'Cloudiness cannot be below 0%'), django.core.validators.MaxValueValidator(100, 'Cloudiness cannot exceed 100%')], verbose_name='Cloudiness (%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='country_code',
            field=models.CharField(help_text='ISO country code (e.g., RU, US, GB)', max_length=10, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when this weather record was created in the database', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='feels_like',
            field=models.FloatField(help_text='Human perception of weather in Celsius', verbose_name='Feels Like (°C)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(help_text='Humidity percentage', validators=[django.core.validators.MinValueValidator(0, 'Humidity cannot be below 0%'), django.core.validators.MaxValueValidator(100, 'Humidity cannot exceed 100%')], verbose_name='Humidity (%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this weather record is active and should be displayed', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='latitude',
            field=models.FloatField(help_text='Geographical latitude coordinate of the location', validators=[django.core.validators.MinValueValidator(-90.0, 'Latitude must be between -90 and 90'), django.core.validators.MaxValueValidator(90.0, 'Latitude must be between -90 and 90')], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='longitude',
            field=models.FloatField(help_text='Geographical longitude coordinate of the location', validators=[django.core.validators.MinValueValidator(-180.0, 'Longitude must be between -180 and 180'), django.core.validators.MaxValueValidator(180.0, 'Longitude must be between -180 and 180')], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.IntegerField(help_text='Atmospheric pressure in hectopascal (hPa)', validators=[django.core.validators.MinValueValidator(800, 'Pressure is unlikely below 800 hPa'), django.core.validators.MaxValueValidator(1100, 'Pressure is unlikely above 1100 hPa')], verbose_name='Pressure (hPa)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sunrise',
            field=models.TimeField(help_text='Sunrise time for the location', verbose_name='Sunrise'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sunset',
            field=models.TimeField(help_text='Sunset time for the location', verbose_name='Sunset'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_max',
            field=models.FloatField(help_text='Maximum temperature at the moment in Celsius', verbose_name='Maximum Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_min',
            field=models.FloatField(help_text='Minimum temperature at the moment in Celsius', verbose_name='Minimum Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(help_text='Temperature in Celsius degrees', verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='timezone_offset',
            field=models.IntegerField(help_text='Shift in seconds from UTC for the location', verbose_name='Timezone Offset (seconds)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when this weather record was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='visibility',
            field=models.IntegerField(blank=True, help_text='Visibility in meters. Maximum value is 10km', null=True, validators=[django.core.validators.MinValueValidator(0, 'Visibility cannot be negative')], verbose_name='Visibility (meters)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_description',
            field=models.CharField(help_text='Weather condition within the group', max_length=100, verbose_name='Weather Description'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_icon',
            field=models.CharField(help_text='Weather icon code for visual representation', max_length=10, verbose_name='Weather Icon'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_id',
            field=models.IntegerField(help_text='OpenWeatherMap weather condition ID', verbose_name='Weather ID'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_main',
            field=models.CharField(help_text='Group of weather parameters (e.g., Clouds, Rain, Clear)', max_length=50, verbose_name='Weather Main'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_degree',
            field=models.IntegerField(help_text='Wind direction in degrees (meteorological)', validators=[django.core.validators.MinValueValidator(0, 'Wind degree must be between 0 and 360'), django.core.validators.MaxValueValidator(360, 'Wind degree must be between 0 and 360')], verbose_name='Wind Degree'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_gust',
            field=models.FloatField(blank=True, help_text='Wind gust in meters per second', null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Wind gust cannot be negative')], verbose_name='Wind Gust (m/s)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(help_text='Wind speed in meters per second', validators=[django.core.validators.MinValueValidator(0.0, 'Wind speed cannot be negative')], verbose_name='Wind Speed (m/s)'),
        ),
    ]
