# Generated by Django 5.1.5 on 2025-10-10 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0004_alter_author_biography_alter_author_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='weather',
            name='simple_weat_api_tim_1435b5_idx',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='api_timestamp',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='feels_like',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='sunset',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temp_max',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temp_min',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='timezone_offset',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather_icon',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather_id',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_degree',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_gust',
        ),
        migrations.AlterField(
            model_name='weather',
            name='city_name',
            field=models.CharField(help_text='Name of the city for weather data', max_length=100, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='clouds',
            field=models.IntegerField(help_text='Cloudiness percentage', validators=[django.core.validators.MinValueValidator(0, 'Cloudiness too low'), django.core.validators.MaxValueValidator(100, 'Cloudiness too high')], verbose_name='Cloudiness (%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(help_text='Humidity percentage', validators=[django.core.validators.MinValueValidator(0, 'Humidity too low'), django.core.validators.MaxValueValidator(100, 'Humidity too high')], verbose_name='Humidity (%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether weather record is active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.IntegerField(help_text='Atmospheric pressure in hPa', validators=[django.core.validators.MinValueValidator(800, 'Pressure too low'), django.core.validators.MaxValueValidator(1100, 'Pressure too high')], verbose_name='Pressure (hPa)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(help_text='Temperature value', verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when record was updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_main',
            field=models.CharField(help_text='Weather parameters group', max_length=50, verbose_name='Weather Main'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(help_text='Wind speed in meters per second', validators=[django.core.validators.MinValueValidator(0.0, 'Wind speed negative')], verbose_name='Wind Speed (m/s)'),
        ),
    ]
