# Generated by Django 5.1.5 on 2025-10-10 18:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0005_remove_weather_simple_weat_api_tim_1435b5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='api_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when data was received', verbose_name='API Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='feels_like',
            field=models.FloatField(default=0.0, help_text='Human perception of temperature', verbose_name='Feels Like'),
        ),
        migrations.AddField(
            model_name='weather',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='Geographical latitude coordinate', validators=[django.core.validators.MinValueValidator(-90.0, 'Latitude too low'), django.core.validators.MaxValueValidator(90.0, 'Latitude too high')], verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='Geographical longitude coordinate', validators=[django.core.validators.MinValueValidator(-180.0, 'Longitude too low'), django.core.validators.MaxValueValidator(180.0, 'Longitude too high')], verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='sunrise',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Sunrise time', verbose_name='Sunrise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='sunset',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Sunset time', verbose_name='Sunset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_max',
            field=models.FloatField(default=0.0, help_text='Maximum temperature', verbose_name='Max Temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_min',
            field=models.FloatField(default=0.0, help_text='Minimum temperature', verbose_name='Min Temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='timezone_offset',
            field=models.IntegerField(default=0, help_text='Shift in seconds from UTC', verbose_name='Timezone Offset'),
        ),
        migrations.AddField(
            model_name='weather',
            name='visibility',
            field=models.IntegerField(blank=True, help_text='Visibility in meters', null=True, verbose_name='Visibility (m)'),
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_icon',
            field=models.CharField(default='', help_text='Weather icon code', max_length=20, verbose_name='Weather Icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_id',
            field=models.IntegerField(default=0, help_text='OpenWeatherMap weather condition ID', verbose_name='Weather ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_degree',
            field=models.IntegerField(default=0, help_text='Wind direction in degrees', validators=[django.core.validators.MinValueValidator(0, 'Wind degree too low'), django.core.validators.MaxValueValidator(360, 'Wind degree too high')], verbose_name='Wind Degree'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='clouds',
            field=models.IntegerField(default=0, help_text='Cloudiness percentage', validators=[django.core.validators.MinValueValidator(0, 'Cloudiness too low'), django.core.validators.MaxValueValidator(100, 'Cloudiness too high')], verbose_name='Cloudiness (%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='country_code',
            field=models.CharField(help_text='ISO country code (e.g., RU, US, GB)', max_length=20, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(default=0, help_text='Humidity percentage', validators=[django.core.validators.MinValueValidator(0, 'Humidity too low'), django.core.validators.MaxValueValidator(100, 'Humidity too high')], verbose_name='Humidity (%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.IntegerField(default=1013, help_text='Atmospheric pressure in hPa', validators=[django.core.validators.MinValueValidator(800, 'Pressure too low'), django.core.validators.MaxValueValidator(1100, 'Pressure too high')], verbose_name='Pressure (hPa)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(default=0.0, help_text='Temperature value in Celsius', verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(default=0.0, help_text='Wind speed in meters per second', validators=[django.core.validators.MinValueValidator(0.0, 'Wind speed negative')], verbose_name='Wind Speed (m/s)'),
        ),
    ]
