# Generated by Django 5.1.5 on 2025-10-10 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0006_weather_api_timestamp_weather_feels_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='api_timestamp',
            field=models.DateTimeField(help_text='Time when data was received from API', verbose_name='API Timestamp'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='clouds',
            field=models.IntegerField(help_text='Cloudiness percentage', validators=[django.core.validators.MinValueValidator(0, 'Cloudiness too low'), django.core.validators.MaxValueValidator(100, 'Cloudiness too high')], verbose_name='Cloudiness (%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='country_code',
            field=models.CharField(help_text='ISO country code (e.g., RU, US, GB)', max_length=10, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='feels_like',
            field=models.FloatField(help_text='Human perception of temperature', verbose_name='Feels Like'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(help_text='Humidity percentage', validators=[django.core.validators.MinValueValidator(0, 'Humidity too low'), django.core.validators.MaxValueValidator(100, 'Humidity too high')], verbose_name='Humidity (%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.IntegerField(help_text='Atmospheric pressure in hPa', validators=[django.core.validators.MinValueValidator(800, 'Pressure too low'), django.core.validators.MaxValueValidator(1100, 'Pressure too high')], verbose_name='Pressure (hPa)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_max',
            field=models.FloatField(help_text='Maximum temperature', verbose_name='Max Temperature'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_min',
            field=models.FloatField(help_text='Minimum temperature', verbose_name='Min Temperature'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(help_text='Temperature value in Kelvin', verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='timezone_offset',
            field=models.IntegerField(help_text='Shift in seconds from UTC', verbose_name='Timezone Offset'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_icon',
            field=models.CharField(help_text='Weather icon code', max_length=10, verbose_name='Weather Icon'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_degree',
            field=models.IntegerField(help_text='Wind direction in degrees', validators=[django.core.validators.MinValueValidator(0, 'Wind degree too low'), django.core.validators.MaxValueValidator(360, 'Wind degree too high')], verbose_name='Wind Degree'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(help_text='Wind speed in meters per second', validators=[django.core.validators.MinValueValidator(0.0, 'Wind speed negative')], verbose_name='Wind Speed (m/s)'),
        ),
    ]
